# ===== USER STATE =====

STATE_WAIT_COIN = "WAIT_COIN"
STATE_WAIT_TIMEFRAME = "WAIT_TIMEFRAME"
STATE_MAIN_MENU = "MAIN_MENU"
STATE_ADMIN_MENU = "ADMIN_MENU"


# ===== USER PLAN =====

PLAN_FREE = "FREE"
PLAN_PRO = "PRO"


# ===== TIMEFRAME =====

TF_5M = "5m"
TF_15M = "15m"
TF_1H = "1h"
TF_4H = "4h"
TF_1D = "1d"


# ===== CALLBACK DATA =====

CB_TF_5M = "TF_5M"
CB_TF_15M = "TF_15M"
CB_TF_1H = "TF_1H"
CB_TF_4H = "TF_4H"
CB_TF_1D = "TF_1D"

CB_FREE_ANALYSIS = "FREE_ANALYSIS"
CB_AI_ANALYSIS = "AI_ANALYSIS"

CB_PROFILE = "PROFILE"
CB_CHART = "CHART"

CB_CHANGE_COIN = "CHANGE_COIN"
CB_CHANGE_TIMEFRAME = "CHANGE_TIMEFRAME"